version: '2'

services:
  mariadb:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    ports:
      - 9022:3306
    volumes:
      - ./data/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mypw2024
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=root

  # myadmin:
  #   image: phpmyadmin
  #   restart: always
  #   ports:
  #     - 9021:80
  #   links:
  #     - mariadb:db
  #   environment:
  #     - MYSQL_USER=root
  #     - MYSQL_PASSWORD=mypw2024

  nextcloud:
    image: nextcloud
    container_name: piplex_nextcloud
    restart: always
    ports:
      - 9020:80
    links:
      - mariadb:mysql
    volumes:
      - ./data/nextcloud:/var/www/html 
      - ./data/apps:/var/www/html/custom_apps 
      - ./data/config:/var/www/html/config 
      - ./data/data:/var/www/html/data 
    environment:
      - MYSQL_PASSWORD=mypw2024
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=root
      - MYSQL_HOST=mariadb