- name: Entferne Snap von Ubuntu
  hosts: all
  become: yes  # Benötigt sudo-Rechte

  tasks:
  - name: Finde alle installierten Snap-Pakete
    ansible.builtin.shell: snap list | awk '/^-/ {print $1}' | grep -v Name
    register: snap_packages
    ignore_errors: yes

  - name: Entferne Snap-Pakete
    ansible.builtin.shell: snap remove {{ item }}
    with_items: "{{ snap_packages.stdout_lines }}"
    when: snap_packages.stdout != ""

  - name: Deinstalliere snapd
    ansible.builtin.apt:
      name: snapd
      state: absent
      purge: yes

  - name: Entferne übriggebliebene Snap-Verzeichnisse
    ansible.builtin.file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /var/cache/snapd/
      - /var/lib/snapd/
      - /var/snap/
    ignore_errors: yes
